name: Build and Release

on:
  push:
    branches:
      - main
      - dev
      - feature/**

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: fakedata
  IMAGE_TAG: ${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  ## ===============================
  ## 1. Build Application + Push ECR
  ## ===============================
  buildApplication:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # - name: Run Unit Tests
      #   run: ./mvnw test

#      - name: Run SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@v2
#        with:
#          projectBaseDir: .
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Spring Boot app
        run: ./mvnw clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

  ## ===============================
  ## 2. Update GitOps Repo (Helm)
  ## ===============================
  processGitOps:
    runs-on: ubuntu-latest
    
    needs: buildApplication
    
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: duongaity/fakedata-gitops
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update image tag in values.yaml
        run: |
          echo "Root level:"
          ls -al
          cd nonprod
          sed -i "s/tag: \".*\"/tag: \"${{ github.run_id }}\"/" values.yaml

      - name: Commit and push changes
        run: |
          git config user.name "Duong Aity"
          git config user.email "duongaity@gmail.com"
          git add .
          git commit -m "chore: update image tag to ${IMAGE_TAG}"
          git push origin main
